# Generated by Django 5.1.2 on 2024-11-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('maticni_broj', models.CharField(max_length=10)),
                ('adresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiveClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('maticni_broj', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VlasnikClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=25)),
                ('prezime', models.CharField(max_length=50)),
                ('oib', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=25)),
                ('prezime', models.CharField(max_length=50)),
                ('oib', models.CharField(max_length=10)),
                ('clanstvo', models.ManyToManyField(to='diveapp.diveclub')),
            ],
        ),
        migrations.CreateModel(
            name='locacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25)),
                ('coordinate', models.CharField(max_length=100)),
                ('clanstvo', models.ManyToManyField(to='diveapp.dc')),
            ],
        ),
        migrations.AddField(
            model_name='diveclub',
            name='vlasnik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diveapp.vlasnikclub'),
        ),
    ]
