# Generated by Django 5.1.2 on 2024-12-26 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diveapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacija',
            name='clanstvo',
        ),
        migrations.AddField(
            model_name='diveclub',
            name='stvoreno',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='diver',
            name='stvoreno',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='locacija',
            name='stvoreno',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vlasnikclub',
            name='stvoreno',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='DC',
        ),
    ]
