# Generated by Django 5.1.2 on 2024-12-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diveapp', '0002_remove_locacija_clanstvo_diveclub_stvoreno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diver',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diver', to=settings.AUTH_USER_MODEL),
        ),
    ]
