# Generated by Django 5.1.2 on 2025-01-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diveapp', '0003_diver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacija',
            name='divclub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diveapp.diveclub'),
        ),
    ]
